### PR TITLE
Social media platform's documentation

### PR DESCRIPTION
**Pull request by proffapt**
- Rebased and merged changes from proffapt:feature-social-media to sheharyaar:feature-social-media for obvious reasons
- Now this will be left for review by all contributors; @thealphadollar already approved these changes, will be waiting for @sheharyaar 's comments to merge these changes to main branch.

Why not change the merge technique to Rebase and Merge for better management of the merges and since rebase retains the linear commit history, will be easy for rollbacks and quantum level changes.
This is just a suggestion; keenly open for suggestions and corrections with this ideology, I have a bit of experience in contributing.. not in  accepting contributions

### CODE REVIEW

**Review by sheharyaar — APPROVED** [review]
LGTM

**Comment by sheharyaar** [comment]
> change the merge technique to Rebase and Merge

Yeah we can do this. No issues

**Comment by proffapt** [comment]
cool, and what's the plan about the branch?
shall it be deleted after the merge?
@sheharyaar

**Comment by sheharyaar** [comment]
Let's let it stay and remove them in case there are many branches

**Pull request merged**
